# Generated by Django 4.1.7 on 2023-03-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-scores']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.TextField(default='', max_length=15),
        ),
    ]
